[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/admin-auth"
  to = "/.netlify/functions/admin-auth"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin-auth/*"
  to = "/.netlify/functions/admin-auth"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin-verify"
  to = "/.netlify/functions/admin-verify"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin-verify/*"
  to = "/.netlify/functions/admin-verify"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin-data"
  to = "/.netlify/functions/admin-data"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin-data/*"
  to = "/.netlify/functions/admin-data"
  status = 200
  force = true

[[redirects]]
  from = "/_api/gas"
  to = "/.netlify/functions/gas-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/_api/gas/*"
  to = "/.netlify/functions/gas-proxy"
  status = 200
  force = true
